version: "3.1"

services:
  client:
    build:
      context: ./client
    restart: unless-stopped
    ports:
      - 8080:8080

  cars:
    build:
      context: ./cars
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./cars:/usr/src/app/cars

  visits:
    build:
      context: ./visits
    restart: unless-stopped
    ports:
      - 3333:3333
    volumes:
      - ./visits:/usr/src/app/visits