version: "3.1"

services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"

  mongo_auth:
    container_name: mongo_auth
    image: mongo
    ports:
      - "27044:27044"

  client:
    container_name: client
    build:
      context: ./client
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./client:/usr/src/app/client

  cars:
    container_name: cars
    build:
      context: ./cars
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./cars:/usr/src/app/cars
    depends_on:
      - mongodb

  #visits:
  #  build:
  #    context: ./visits
  #  restart: unless-stopped
  #  ports:
  #    - 3333:3333
  #  volumes:
  #    - ./visits:/usr/src/app/visits
  #  depends_on:
  #    - mongodb

  auth:
    container_name: auth
    build:
      context: ./auth
    restart: unless-stopped
    ports:
      - 4444:4444
    volumes:
      - ./auth:/usr/src/app/auth
      - /usr/src/app/auth/node_modules
    depends_on:
      - mongo_auth