version: "3.1"

services:
  client:
    build:
      context: ./client
    restart: unless-stopped
    ports:
      - 8080:8080

  server:
    build:
      context: ./server
    restart: unless-stopped
    ports:
      - 3000:3000